import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Get An Expert",
};

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-semibold text-black dark:text-zinc-50">
        {title}
      </h2>
      <div className="mt-2 space-y-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-16">
      <h1 className="text-3xl font-semibold text-black dark:text-zinc-50">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-zinc-500">
        Effective date: July 13, 2026 · Version 1.0
      </p>

      <Section title="1. Acceptance">
        <p>
          By installing get-an-expert-mcp or using the Get An Expert API or
          website (together, the &quot;Service&quot;), you agree to these
          terms. The Service is intended for software developers aged 18 or
          older.
        </p>
      </Section>

      <Section title="2. What the Service is (and isn't)">
        <p>
          Get An Expert helps you get unstuck in AI coding sessions. Today,
          suggestions are <strong>generated by AI</strong> (Anthropic&apos;s
          Claude) from the session summary you approve and send. They are
          informational only — not professional advice — and may be wrong,
          incomplete, or unsuitable for your situation. Always review
          suggestions before applying them, especially to production systems.
          When human expert services launch, they will be described in
          separate terms.
        </p>
      </Section>

      <Section title="3. Consent-based sending">
        <p>
          The software sends data to us only when you explicitly approve a
          specific request. You are responsible for reviewing what will be
          sent; the software shows you the summary and redacts common secret
          formats on your machine first, but no automated redaction is
          perfect.
        </p>
      </Section>

      <Section title="4. Acceptable use">
        <p>
          Don&apos;t abuse the Service: no attempts to breach or overload it,
          no submitting content you don&apos;t have the right to share, no use
          that violates applicable law, and no automated bulk submissions
          outside the intended stuck-session flow.
        </p>
      </Section>

      <Section title="5. Your content stays yours">
        <p>
          You retain all rights to everything you submit. You grant us a
          limited license to process your submission solely to provide the
          Service (generating your suggestion, optional expert follow-up, and
          the retention described in the Privacy Policy). We claim no other
          rights.
        </p>
      </Section>

      <Section title="6. Disclaimers and limitation of liability">
        <p>
          The Service is provided &quot;as is&quot; without warranties of any
          kind. To the maximum extent permitted by law, we are not liable for
          any indirect, incidental, special, consequential, or exemplary
          damages, or for losses resulting from applying a suggestion to your
          code or systems. Our total liability for any claim is limited to the
          greater of $50 or the amount you paid us in the 12 months before the
          claim.
        </p>
      </Section>

      <Section title="7. Privacy">
        <p>
          Our{" "}
          <Link className="underline" href="/privacy">
            Privacy Policy
          </Link>{" "}
          is part of these terms and describes exactly what we collect and how
          to delete it.
        </p>
      </Section>

      <Section title="8. Termination">
        <p>
          You can stop using the Service at any time by uninstalling the
          software; stored requests still auto-delete on their 30-day
          schedule, or immediately via your deletion links. We may suspend or
          terminate access for abuse.
        </p>
      </Section>

      <Section title="9. Governing law">
        <p>
          These terms are governed by the laws of the jurisdiction in which we
          operate, without regard to conflict-of-law rules. Disputes will be
          resolved in the courts of that jurisdiction.
        </p>
      </Section>

      <Section title="10. Changes">
        <p>
          We may update these terms; material changes will be posted here with
          a new effective date before they apply. Continued use after changes
          means acceptance.
        </p>
      </Section>

      <p className="mt-10 text-sm text-zinc-500">
        <Link className="underline" href="/">
          ← Back to home
        </Link>
      </p>
    </main>
  );
}
